zenix/shop/urls.py
from django.contrib import admin
from django.urls import include, path
from .import views
from shop.views import index


app_name='shop'
urlpatterns = [
    path('', views.index, name='index'),
    path('products/', views.product_list_view, name='product-list'),

    path('product/<pid>/', views.product_detail_view, name='product-detail'),

    path('category-list/', views.category_list_view, name='category-list'),
    path('category/<cid>/', views.category_product_list_view, name='category-product-list'),

    path('search/',views.search_view,name='search'),
    path('filter-products/', views.filter_product,name='filter-product')
]

zenix/zenix/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),
    path('accounts/', include('accounts.urls')),
    path('admin_panel/', include('admin_panel.urls')),
    path('admin_auth/', include('admin_auth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

zenix/shop/models.py
from django.db import models
from shortuuidfield import ShortUUIDField
from django.utils.html import mark_safe
from unicodedata import decimal
from accounts.models import Account
# Create your models here.

STATUS_CHOICE = (
   ('process', 'Processing'),
   ('shipped', 'Shipped'),
   ('delivered', 'Delivered'),
)

STATUS = (
   ('draft', 'Draft'),
   ('disabled', 'Disabled'),
   ('rejected', 'Rejected'),
   ('in_review', 'In_Review'),
   # ('published', 'Published'),
)

RATING = (
   (1, '⭐☆☆☆☆'),
   (2, '⭐⭐☆☆☆'),
   (3, '⭐⭐⭐☆☆'),
   (4, '⭐⭐⭐⭐☆'),
   (5, '⭐⭐⭐⭐⭐'),
)

class Category(models.Model):
   cid = ShortUUIDField(unique=True, max_length=30)

   title = models.CharField(max_length=100, default='Watches')
   image = models.ImageField(upload_to='category', default='category.jpg')
   is_blocked =models.BooleanField(default=False)

   class Meta:
      verbose_name_plural = 'Categories'
   
   def category_image(self):
      return mark_safe("<img src='%s' width ='50' height='50' />" % (self.image.url))
   
   def __str__(self):
      return self.title
   
##################################################################

#######################################################################################

class Product(models.Model):
   pid = ShortUUIDField(unique=True, max_length=30)

   user = models.ForeignKey(Account, on_delete=models.SET_NULL, null=True)
   category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, related_name = 'category')

   title = models.CharField(max_length=100, default='Branded watch')
   image = models.ImageField(upload_to='product', default ='product.jpg')
   description = models.TextField(null=True, blank=True, default='This is the product')

   price = models.DecimalField(max_digits=10, decimal_places=2, default='1200.00')
   old_price = models.DecimalField(max_digits=10, decimal_places=2, default='1000.00')

   specifications = models.TextField(null=True, blank=True)


##################
   stock_count = models.CharField(max_length = 100,default = "10",null=True, blank=True)
   manufacturing_date=models.DateTimeField(auto_now_add=False,null=True, blank=True)
   return_policy= models.CharField(max_length = 100,default = "10", null=True, blank=True)
   warrenty = models.CharField(max_length = 100,default = "1", null=True, blank=True)
####################

   product_status = models.CharField(choices=STATUS, max_length=10, default='in_review')

   status = models.BooleanField(default=True)
   in_stock = models.BooleanField(default=True)
   featured = models.BooleanField(default=False)
   digital = models.BooleanField(default=False)

   sku = ShortUUIDField(unique=True, max_length=10)

   date = models.DateTimeField(auto_now_add=True)
   updated = models.DateTimeField(null=True, blank=True)

   

   class Meta:
       verbose_name_plural = 'Products'

   def product_image(self):
       return mark_safe("<img src='%s' width ='50' height='50' />" % (self.image.url))
   
   def __str__(self):
       return self.title
   
   def get_percentage(self):
       new_price = (self.price / self.old_price) * 100
       return new_price
   
class ProductImages(models.Model):
    images = models.ImageField(upload_to='product_images',default='product.jpg')
    product = models.ForeignKey(Product,related_name='p_images', on_delete=models.SET_NULL, null=True)
    date = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'Products'

    def product_image(self):
        return mark_safe("<img src='%s' width ='50' height='50' />" % (self.images.url))

    def __str__(self):
        return str(self.product) 
        





     


  

zenix/shop/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from shop.models import Category, Product, ProductImages
from django.db.models import Count
from django.views.decorators.cache import never_cache
from django.views.decorators.cache import cache_control
from django.core.paginator import Paginator
from django.http import JsonResponse
from django.template.loader import render_to_string


# Create your views here.
@never_cache
@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def index(request):
  # products = Product.objects.all().order_by('id')
  blocked_categories =Category.objects.filter(is_blocked =True)
  products = Product.objects.filter(product_status='draft',featured=True)
  latest = Product.objects.filter(status=True).order_by("-id")[:10]
  categories =Category.objects.filter(is_blocked =False)
  user=request.user
  context = {
        "products":products,
        "latest":latest,
        "categories":categories,
        'user'  : user
  }
  return render(request, 'shop/index.html',context)

#################################################################
#listing products on the shop page:  

def product_list_view(request):
   # products = Product.objects.all().order_by('id')
  blocked_categories =Category.objects.filter(is_blocked =True)
  products = Product.objects.filter(product_status='draft')
  categories =Category.objects.filter(is_blocked =False)
  p=Paginator(Product.objects.filter(status =True).exclude(category__in=blocked_categories),10)
  page=request.GET.get('page')
  productss=p.get_page(page)

  context = {
        "products":products,
        "categories":categories,
        "productss":productss
  }
    
  return render(request,'shop/product_list.html', context)
#########################################################################

def category_list_view(request):
   # products = Product.objects.all().order_by('id')
  # categories = Category.objects.all().annotate(product_count=Count('product'))
  category = Category.objects.filter(is_blocked=False)


  context = {
    'category' : category
  }

  return render(request, 'shop/category-list.html',context)

###############################################################

def category_product_list_view(request, cid):
  category = Category.objects.get(cid=cid)
  products = Product.objects.filter(status=True,category=category)

  context = {
    'category' : category,
    'products' : products,
  }
  return render(request,'shop/category-product-list.html',context)

########################################################################################fgnhrhhh

def product_detail(request,pid):
    product = Product.objects.get(pid = pid)
    p_image =product.p_images.all()
    category = Category.objects.all()
    products = Product.objects.filter(category=product.category).exclude(pid=pid)[:4]
    
    
    context={
        "product":product,
        "p_image":p_image,
        "category":category,
        "products":products
        
        
        
    }
    return render (request,'shop/product_detail.html',context)

def search_view(request):
    query =request.GET.get('q')
    print(query)
    
    products =Product.objects.filter(title__icontains =query)
    print(products)
    
    context ={
        'products':products,
        'query': query
        
    }
    
    return render(request,'shop/search.html',context)


# def filter_product(request):
#     categories =request.GET.getlist('Category[]')
    
#     products =Product.objects.filter(status=True).order_by('-id').distinct()
    
#     if len(categories) > 0:
#         products=products.filter(category__id__in=categories).distinct()
        
#     data =render_to_string('app1/async/product-list.html',{"products":products})
#     return JsonResponse ({"data":data})
    
def filter_product(request):    
    try:
            categories = request.GET.getlist('category[]')
            print("Selected Categories:", categories)

            products = Product.objects.filter(status=True).order_by('-id').distinct()
            print("All Products:", products)
            print("Selected Categories:", categories)

            if len(categories) > 0:
                products = products.filter(category__cid__in=categories).distinct()
                print("Filtered Product:", products)

            data = render_to_string('shop/async/product-list.html', {"products": products})
            return JsonResponse({"data": data})
    except Exception as e:
            return JsonResponse({"error": str(e)})





def product_detail_view(request,pid):
   product = Product.objects.get(pid=pid)
  #  product = get_object_or_404(product,pid=pid)

   p_image = product.p_images.all()

   context = {
     'p' : product,
     'p_image' : p_image,
   }
   return render(request, 'shop/product-detail.html',context)
  

zenix/templates/shop/category-product-list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <main class="main">
        <div class="page-header breadcrumb-wrap">
            <div class="container">
                <div class="breadcrumb">
                    <a href="index.html" rel="nofollow">Home</a>
                    <span></span> Shop
                    <span></span> {{category.title}}
                </div>
            </div>
        </div>
        <section class="mt-50 mb-50">
            <div class="container">
                <div class="row">
                    
                    <div class="col-lg-12">
                      <div class="single-header mb-50">
                        <h1 class="font-xxl text-brand">{{category.title}}</h1>
                        <div class="shop-product-fillter">
                          <div class="totall-product">
                              <p> We found <strong class="text-brand">{{products.count}}</strong> item{{products.count|pluralize}} for you!</p>
                          </div>
                          <div class="sort-by-product-area">
                              <div class="sort-by-cover mr-10">
                                  <div class="sort-by-product-wrap">
                                      <div class="sort-by">
                                          <span><i class="fi-rs-apps"></i>Show:</span>
                                      </div>
                                      <div class="sort-by-dropdown-wrap">
                                          <span> 50 <i class="fi-rs-angle-small-down"></i></span>
                                      </div>
                                  </div>
                                  <div class="sort-by-dropdown">
                                      <ul>
                                          <li><a class="active" href="#">50</a></li>
                                          <li><a href="#">100</a></li>
                                          <li><a href="#">150</a></li>
                                          <li><a href="#">200</a></li>
                                          <li><a href="#">All</a></li>
                                      </ul>
                                  </div>
                              </div>
                              <div class="sort-by-cover">
                                  <div class="sort-by-product-wrap">
                                      <div class="sort-by">
                                          <span><i class="fi-rs-apps-sort"></i>Sort by:</span>
                                      </div>
                                      <div class="sort-by-dropdown-wrap">
                                          <span> Featured <i class="fi-rs-angle-small-down"></i></span>
                                      </div>
                                  </div>
                                  <div class="sort-by-dropdown">
                                      <ul>
                                          <li><a class="active" href="#">Featured</a></li>
                                          <li><a href="#">Price: Low to High</a></li>
                                          <li><a href="#">Price: High to Low</a></li>
                                          <li><a href="#">Release Date</a></li>
                                          <li><a href="#">Avg. Rating</a></li>
                                      </ul>
                                  </div>
                              </div>
                          </div>
                      </div>
                        <!-- {%for c in categories%}
                        <div class="entry-meta meta-1 font-xs mt-15 mb-15">
                            <span class="post-by">{{c.category.count}} product{{c.category.count|pluralize}}</span>
                            
                        </div>
                        {% endfor %} -->
                        
                    
                        <div class="row product-grid-3">

                            {% for p in products%}
                            <div class="col-lg-3 col-md-4 col-12 col-sm-6">
                                <div class="product-cart-wrap mb-30">
                                    <div class="product-img-action-wrap">
                                        <div class="product-img product-img-zoom">
                                            <a href="shop-product-right.html">
                                                <a href="{% url 'shop:product-detail' p.pid %}"><img class="default-img" src="{{p.image.url}}" alt=""></a>
                                                <img class="hover-img" src="{{p.image.url}}" alt="">
                                            </a>
                                        </div>
                                        <div class="product-action-1">
                                            <a aria-label="Quick view" class="action-btn hover-up" data-bs-toggle="modal" data-bs-target="#quickViewModal"><i class="fi-rs-eye"></i></a>
                                            <a aria-label="Add To Wishlist" class="action-btn hover-up" href="shop-wishlist.html"><i class="fi-rs-heart"></i></a>
                                            <a aria-label="Compare" class="action-btn hover-up" href="shop-compare.html"><i class="fi-rs-shuffle"></i></a>
                                        </div>
                                        <div class="product-badges product-badges-position product-badges-mrg">
                                            <span class="hot">-{{p.get_percentage|floatformat:0}}%</span>
                                        </div>
                                    </div>
                                    <div class="product-content-wrap">
                                        <div class="product-category">
                                            <a href="{% url 'shop:product-detail' p.pid %}">{{p.category}}</a>
                                        </div>
                                        <h2><a href="{% url 'shop:product-detail' p.pid %}">{{p.title}}</a></h2>
                                        <div class="rating-result" title="90%">
                                            <span>
                                                <span>90%</span>
                                            </span>
                                        </div>
                                        <div class="product-price">
                                            <span>{{p.price}} </span>
                                            <span class="old-price">{{p.old_price}}</span>
                                        </div>
                                        <div class="product-action-1 show">
                                            <a aria-label="Add To Cart" class="action-btn hover-up" href="shop-cart.html"><i class="fi-rs-shopping-bag-add"></i></a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            {% endfor%}
                            
                        </div>
                        <!--pagination-->
                        <div class="pagination-area mt-15 mb-sm-5 mb-lg-0">
                            <nav aria-label="Page navigation example">
                                
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </main>
    {%endblock%}