zenix/accounts/urls.py
from django.urls import path
from accounts import views
  
app_name = 'accounts'

urlpatterns = [
  path('sign-up/', views.register_view, name='signup'),
  path('login/', views.login_view, name='login'),
  path('logout/', views.logoutUser, name='logout'),
  path('sign-up/otp_verification',views.otp_verification,name="otp_verification"),
  path('login_otp/',views.login_otp,name ='login_otp'),
  path('login/otp_verification_login',views.otp_verification_login,name="otp_verification_login"),
  

]

zenix/shop/urls.py
from django.contrib import admin
from django.urls import include, path
from .import views
from shop.views import index


app_name='shop'
urlpatterns = [
    path('', views.index, name='index'),
    path('products/', views.product_list_view, name='product-list'),

    path('product/<pid>/', views.product_detail_view, name='product-detail'),

    path('category-list/', views.category_list_view, name='category-list'),
    path('category/<cid>/', views.category_product_list_view, name='category-product-list'),

    path('search/',views.search_view,name='search'),
    path('filter-products/', views.filter_product,name='filter-product')
]

zenix/zenix/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),
    path('accounts/', include('accounts.urls')),
    path('admin_panel/', include('admin_panel.urls')),
    path('admin_auth/', include('admin_auth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

zenix/accounts/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import AbstractBaseUser,BaseUserManager,PermissionsMixin
from django.db.models import Q



class UserManager(BaseUserManager):
  def create_user(self,first_name,last_name,username,email,password=None):
    if not email:
      raise ValueError('User must an email address')
    
    if not username:
      raise ValueError('User must have a username')

    user = self.model(
      email = self.normalize_email(email),
      username = username,
      first_name = first_name,
      last_name = last_name
    )
    user.set_password(password)
    user.save(using =self.db)
    return user
  
  def create_superuser(self,first_name,last_name,username,email,password=None):
    user = self.create_user(
      email = self.normalize_email(email),
      username=username, 
      password=password,
      first_name=first_name,
      last_name=last_name,
    )
    user.is_admin = True
    user.is_active = True
    user.is_staff = True
    user.is_superadmin = True
    user.save(using = self.db)
    return user




class Account(AbstractBaseUser,PermissionsMixin):
  first_name = models.CharField(max_length=50)
  last_name = models.CharField(max_length=50)
  username = models.CharField(max_length=100, unique=True)
  email = models.EmailField(max_length=100, unique=True)
  phone_number = models.CharField(max_length=12,blank=True)
  



  #required field

  date_joined = models.DateTimeField(auto_now_add=True)
  last_login = models.DateTimeField(auto_now_add=True)
  created_date = models.DateTimeField(auto_now_add=True)
  modified_date = models.DateTimeField(auto_now_add=True)
  is_admin = models.BooleanField(default =False)
  is_staff = models.BooleanField(default =False)
  is_active = models.BooleanField(default =True)
  is_superadmin = models.BooleanField(default =False)


  USERNAME_FIELD = 'email'
  REQUIRED_FIELDS = ['username', 'first_name','last_name']
  objects = UserManager()



  def __str__(self):
    return self.email
  
  def has_perm(self, perm, obj=None):
        return self.is_admin

  
  def has_module_perms(self,app_label):
    return True


# class Userform(models.Model):
#   # user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
#   username = models.CharField(null=True, max_length=100)
#   email = models.EmailField(null=True)
#   password = models.CharField(null=True, max_length=255)

#   def __str__(self):
#     return self.username

zenix/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from accounts.models import Account

class UserRegisterForm(UserCreationForm):
  first_name = forms.CharField(max_length=30,widget=forms.TextInput(attrs= {"placeholder":"First Name"}), required=True, help_text='Required. 30 characters or fewer.')
  last_name = forms.CharField(max_length=30,widget=forms.TextInput(attrs= {"placeholder":"Last Name"}), required=True, help_text='Required. 30 characters or fewer.')
  email = forms.EmailField(max_length=254,widget=forms.EmailInput(attrs= {"placeholder":"Email"}), required=True, help_text='Required. Enter a valid email address.')
  password1 = forms.CharField(max_length=30,widget=forms.PasswordInput(attrs= {"placeholder":"Password"}), required=True, help_text='Required. 30 characters or fewer.')
  password2 = forms.CharField(max_length=30,widget=forms.PasswordInput(attrs= {"placeholder":"Confirm Password"}), required=True, help_text='Required. 30 characters or fewer.')
  username = forms.CharField(max_length=30,widget=forms.TextInput(attrs= {"placeholder":"Username"}), required=True, help_text='Required. 30 characters or fewer.')

  class Meta:
    model = Account
    fields = ['username', 'first_name', 'last_name', 'email','password1','password2']

zenix/accounts/views.py
from django.shortcuts import render, redirect
from .forms import UserRegisterForm
from django.contrib.auth import login, authenticate, logout
from django.contrib import messages
from accounts.backends import EmailBackend  # Import your custom authentication backend
import random
from django.core.mail import send_mail
from django.contrib.auth.hashers import make_password
from django.views.decorators.cache import never_cache
from django.views.decorators.cache import cache_control
from django.http import HttpResponseRedirect,HttpResponseBadRequest
from django.urls import reverse


from accounts.models import Account  # Import your custom user model



@never_cache
def register_view(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            # user = form.save()
            username = form.cleaned_data.get('username')
            email = form.cleaned_data.get('email')
            password=form.cleaned_data.get('password1')
            request.session["username"]=username
            request.session["password"]=password
            request.session["email"]=email
            messages.success(request, f'Hey {username}, Your account was created succesfully')
            email=request.POST["email"]
            send_otp(request)
            
            
            return render(request,'accounts/otp.html',{"email":email})
            
           
    else:
        form = UserRegisterForm()

    context = {'form': form}
    return render(request, 'accounts/signup.html', context)


#OTP
@never_cache
def send_otp(request):
    s=""
    for x in range(0,4):
        s+=str(random.randint(0,9))
    request.session["otp"]=s
    send_mail("otp for sign up",s,'djangoalerts0011@gmail.com',[request.session['email']],fail_silently=False)
    return render(request,"accounts/otp.html")

@never_cache
def  otp_verification(request):
    if  request.method=='POST':
       
        otp_=request.POST.get("otp")
    if otp_ == request.session["otp"]:
        encryptedpassword=make_password(request.session['password'])
        nameuser=Account(username=request.session['username'],email=request.session['email'],password=encryptedpassword)
        nameuser.save()
        messages.info(request,'signed in successfully...')
        Account.is_active=True
        # user = Account.objects.get(email = request.session['email'])
        # login(request, nameuser)
        # login(request,user)
        return redirect('accounts:login')
    else:
        messages.error(request,"otp doesn't match")
        return render(request,'accounts/otp.html')
    
    
    
    
    
    
@never_cache
def login_view(request):
  
    if request.user.is_authenticated:
      messages.warning(request,f"Hey You are already logged in")
      return redirect("shop:index")
    if request.method == 'POST':
        email = request.POST.get('email')
        password = request.POST.get('password')
        request.session["email"]=email
        print(email,password)
        if not Account.objects.filter(email=email).exists():
            messages.error(request, "Invalid Email Adress")
            return redirect('accounts:login')
        
        if not Account.objects.filter(email=email,is_active=True).exists():
            messages.error(request, "Account blocked ! ! !")
            return redirect('accounts:login') 
        try:
          user = Account.objects.get(email=email)
          user = authenticate(email=email, password=password,backend = EmailBackend)
        

          if user is not None:
              login(request, user)
           
              messages.success(request, 'Login successful.')
              return redirect("shop:index")  # Redirect to the desired page after successful login
          else:
              messages.warning(request, 'Username or Password is incorrect.')

        except:
          messages.warning(request, f'User with {email} doesnot exists')
          
        
    context = {}
    return render(request, 'accounts/login.html', context)



@never_cache
@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def login_otp(request):
    
    if request.user.is_authenticated:
      messages.warning(request,f"Hey You are already logged in")
      return redirect("shop:index")
    if request.method == 'POST':
        email = request.POST.get('email')
        
        request.session["email"]=email
        print(email)
        if not Account.objects.filter(email=email).exists():
            messages.error(request, "Invalid Email Adress")
            return redirect('accounts:login_otp')
        
        if not Account.objects.filter(email=email,is_active=True).exists():
            messages.error(request, "Account blocked ! ! !")
            return redirect('accounts:login_otp') 
        try:
          user = Account.objects.get(email=email)
        #   user = authenticate(email=email)
        

          if user is not None:
            send_otp_login(request)
            return render(request,'accounts/otp_login.html',{"email":email})
        #   
        except:
          messages.warning(request, f'User with {email} doesnot exists')
          

        # #   context = {'form': form}
        #   return render(request, 'userauths/login_otp')
              
        #       login(request, user)
        #       request.session['logged_in'] = True  # Set a session variable if needed
        #     messages.success(request, 'Login successful.')
        #     return redirect("app1:index")  # Redirect to the desired page after successful login
        #   else:
        #       messages.warning(request, 'Username or Password is incorrect.')

    return render(request,'accounts/login_otp.html')
    
    



# login _otp views
@never_cache
@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def send_otp_login(request):
    s=""
    for x in range(0,4):
        s+=str(random.randint(0,9))
    request.session["otp"]=s
    send_mail("otp for sign up",s,'djangoalerts0011@gmail.com',[request.session['email']],fail_silently=False)
    return render(request,"accounts/otp_login.html")


# @never_cache
# @cache_control(no_cache=True, must_revalidate=True, no_store=True)
# def  otp_verification_login(request):
#     if  request.method=='POST':
#         otp_=request.POST.get("otp")
#     if otp_ == request.session["otp"]:
#         # encryptedpassword=make_password(request.session['password'])
#         # nameuser=User(email=request.session['email'])
#         # nameuser.save()
#         messages.info(request,'signed in successfully...')
#         User.is_active=True
       
#         return redirect('app1:index')
#         request.session.pop('otp', None)
#     else:
#         messages.error(request,"otp doesn't match")
#         return render(request,'userauths/otp_login.html')
    
    
@never_cache
@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def otp_verification_login(request):
    if request.method == 'POST':
        otp_ = request.POST.get("otp")
        try:
            if otp_ == request.session["otp"]:
                # Clear the 'otp' session key after successful verification
                request.session.pop('otp', None)

                # Retrieve the user instance from the database
                user = Account.objects.get(email=request.session.get("email"))

                # Set the user as active
                user.is_active = True
                
                user.save()
                

                messages.success(request, 'Account activated successfully.')
                redirect_url = reverse('shop:index')
                return HttpResponseRedirect(redirect_url)  # Replace '/app1/index' with your actual URL
            else:
                messages.error(request, "OTP doesn't match")
                return render(request, 'accounts/otp_login.html')
        except KeyError:
            messages.error(request, 'Session expired. Please try logging in again.')

    return HttpResponseBadRequest("Invalid request method")
    


# ends here
    




    
    
@never_cache
def logoutUser(request):
    logout(request)
    request.session.flush()  # Clear all session data
    messages.success(request, 'You logged out')
    return redirect('shop:index')

zenix/templates/accounts/login.html
<!DOCTYPE html>
<html>
    
<head>
	<title>Login</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">


	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: #ffffff !important;
		}
		.user_card {
			width: 420px;
			margin-top: auto;
			margin-bottom: auto;
			background: #ffffff;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #fff;
			
		}

		.login_btn {
			width: 100%;
			background: #1979b4 !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #f7ba5b !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

		#messages{
			background-color: grey;
			color: #fff;
			padding: 10px;
			margin-top: 10px;
		}
	</style>

</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center" >


					<strong><h3 id="form-title" style="color: black;">LOGIN</h3></strong>
				</div>
				<div class="d-flex justify-content-center form_container">
					<form method="POST" action="" style="width: 320px;">
            {% csrf_token  %}
						<div class="input-group mb-3">
							<!-- <div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div> -->
							<input type="email" name="email" placeholder="Email..." class="form-control">
						</div>
						<div class="input-group mb-2">
							<!-- <div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div> -->
								<input type="password" name="password" placeholder="Password..." class="form-control" >
						</div>

							<div class="d-flex justify-content-center mt-3 login_container">
				 				<input class="btn btn-success login_btn" type="submit" value="Login" style="color: #1271ba;">
				   			</div>
					</form>

				</div>
        <div class="text-center">
        {% for message in messages %}

        {{message}}

        {%endfor%}
			</div>
        <!-- {{form.errors}} -->
				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Don't have an account? <a href="{% url 'accounts:signup' %}" class="ml-2">Sign Up</a>
					</div>
					<div class="d-flex justify-content-center links">
						 <a href="{% url 'accounts:login_otp' %}" class="ml-2">Login with OTP</a>
					</div>
					
			
				</div>
			</div>
		</div>
	</div>
</body>

</html>

zenix/templates/accounts/login_otp.html
<!DOCTYPE html>
<html>
    
<head>
	<title>Login</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">


	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: #ffffff !important;
		}
		.user_card {
			width: 420px;
			margin-top: auto;
			margin-bottom: auto;
			background: #ffffff;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #fff;
			
		}

		.login_btn {
			width: 100%;
			background: #1979b4 !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #f7ba5b !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

		#messages{
			background-color: grey;
			color: #fff;
			padding: 10px;
			margin-top: 10px;
		}
	</style>

	



</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center" >


					<strong><h3 id="form-title" style="color: black;">Login</h3></strong>
				</div>
				<div class="d-flex justify-content-center form_container">
					<form method="POST" action="" style="width: 320px;">
            {% csrf_token  %}
						<div class="input-group mb-3">
							<!-- <div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div> -->
							<input type="email" name="email" placeholder="Email..." class="form-control">
						</div>
						<!-- <div class="input-group mb-2">
							 <div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div> -->
								<!-- <input type="password" name="password" placeholder="Password..." class="form-control" >
						</div> --> 

							<div class="d-flex justify-content-center mt-3 login_container">
				 				<input class="btn btn-success login_btn" type="submit" value="Send OTP" style="color: #1271ba;">
				   			</div>
					</form>

				</div>
        <div class="text-center">
        {% for message in messages %}

        {{message}}

        {%endfor%}
			</div>
        <!-- {{form.errors}} -->
				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Don't have an account? <a href="{% url 'accounts:signup' %}" class="ml-2">Sign Up</a>
            
					</div>
          <div class="d-flex justify-content-center links">
						<a href="{% url 'accounts:login' %}" class="ml-2">Back</a>
            
					</div>
					
			
				</div>
			</div>
		</div>
	</div>
</body>

</html>

zenix/templates/accounts/otp.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Confirm Your Account</title>
    <link rel="stylesheet" href="styles.css">
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
        }
        
        .container {
            width: 300px;
            padding: 16px;
            background-color: #fff;
            margin: 100px auto;
            box-shadow: 0px 0px 5px 0px rgba(0,0,0,0.1);
        }
        
        h1 {
            text-align: center;
            margin-bottom: 24px;
        }
        
        form {
            display: flex;
            flex-direction: column;
        }
        
        label {
            margin-bottom: 8px;
        }
        
        input {
            padding: 8px;
            margin-bottom: 16px;
            border: 1px solid #ddd;
            border-radius: 4px;
        }
        
        button {
            padding: 8px;
            background-color: #007BFF;
            color: #fff;
            font-weight: bold;
            border: none;
            border-radius: 4px;
            cursor: pointer;
        }
        
        button:hover {
            background-color: #0056b3;
        }
    </style>
</head>
<body>
    <div class="container mt-5">
        <div class="text-center">
          <h2 class="font-weight-bold" style="padding-left: 20px;">Confirm Your Account</h2>
        </div>
    
        <form action="{% url 'accounts:otp_verification' %}" method="POST" class="mt-4">
          {% csrf_token %}
          <div class="form-group text-center">
            <label for="otp" class="font-weight-bold" style="padding: 30%;">Enter the OTP</label><br>
            <input type="text" class="form-control-lg" style="padding-left: 115px;"  id="otp" name="otp" placeholder="Enter the OTP" required>
          </div>
          
          <div class="text-center mt-4" style="padding-left: 120px;" >
            <button type="submit" class="btn btn-primary btn-lg">Verify</button>
          </div>
        </form>
      </div>
</body>
{%if messages%}
{%for message in messages%}
<script>alert('{{message}}')</script>
{%endfor%}
{%endif%}
</html>

zenix/templates/accounts/otp_login.html
<!-- <center><strong>CONFRIM YOUR ACCOUNT</strong></center>

<center><p>check the inbox of your email - {{email}} - and enter the otp<p></center>

<body>
    <form action="{% url 'userauths:otp_verification'%}" method="POST">
        {% csrf_token %}
        <center>Enter the otp : <input type="text" placeholder="enter the otp" name="otp"></center><br><br>
        <center><button type="submit">verify</button></center>
    </form>
</body>


{%if messages%}
{%for message in messages%}
<script>alert('{{message}}')</script>
{%endfor%}
{%endif%} -->

<!-- registration/confirm_account.html -->

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Confirm Your Account</title>
    <link rel="stylesheet" href="styles.css">
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
        }
        
        .container {
            width: 300px;
            padding: 16px;
            background-color: #fff;
            margin: 100px auto;
            box-shadow: 0px 0px 5px 0px rgba(0,0,0,0.1);
        }
        
        h1 {
            text-align: center;
            margin-bottom: 24px;
        }
        
        form {
            display: flex;
            flex-direction: column;
        }
        
        label {
            margin-bottom: 8px;
        }
        
        input {
            padding: 8px;
            margin-bottom: 16px;
            border: 1px solid #ddd;
            border-radius: 4px;
        }
        
        button {
            padding: 8px;
            background-color: #007BFF;
            color: #fff;
            font-weight: bold;
            border: none;
            border-radius: 4px;
            cursor: pointer;
        }
        
        button:hover {
            background-color: #0056b3;
        }
    </style>
    <script>
        if (window.history.replaceState) {
            window.history.replaceState(null, null, window.location.href);
        }
    </script>
</head>
<body>
    <div class="container mt-5">
        <div class="text-center">
          <h2 class="font-weight-bold" style="padding-left: 20px;">Confirm Your Account</h2>
        </div>
    
        <form action="{% url 'accounts:otp_verification_login' %}" method="POST" class="mt-4">
          {% csrf_token %}
          <div class="form-group text-center">
            <label for="otp" class="font-weight-bold" style="padding: 30%;">Enter the OTP</label><br>
            <input type="text" class="form-control-lg" style="padding-left: 115px;"  id="otp" name="otp" placeholder="Enter the OTP" required>
          </div>
          
          <div class="text-center mt-4" style="padding-left: 120px;" >
            <button type="submit" class="btn btn-primary btn-lg">Verify</button>
          </div>
        </form>
      </div>
</body>
{%if messages%}
{%for message in messages%}
<script>alert('{{message}}')</script>
{%endfor%}
{%endif%}
</html>

zenix/templates/accounts/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="styles.css">
    <title>Registration</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css"
          integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">

    <style>
      body {
        font-family: Arial, sans-serif;
    }
    
    .container {
        max-width: 420px;
        margin: 50px auto;
        padding: 20px;
        background-color: #f8f9fa;
        border: 1px solid #dee2e6;
        border-radius: 5px;
        padding-right: 40px;
        padding-left: 35px;
    }
    
    .form-group {
        margin-bottom: 15px;
    }
    
    .form-group label {
        display: block;
        margin-bottom: 5px;
    }
    
    .form-group input {
        width: 100%;
        padding: 10px;
        border: 1px solid #ced4da;
        border-radius: 3px;
    }
    
    button[type="submit"] {
        margin-top: 20px;
        width: 100%;
        height: 32px;
        margin-left: 10px;
    }
    button:focus {
      box-shadow: none !important;
      outline: 0px !important;
  }
    </style>
</head>
<body>
    <div class="container">
      {% if form.errors  %}
      <div class="alert alert-danger">
          <strong> {% for field_name, error_list in form.errors.items %}
              {% if field_name == 'password1' %}
                  Password: {{ error_list|join:", " }}
              {% elif field_name == 'password2' %}
                  Confirm Password: {{ error_list|join:", " }}
              {% else %}
                  {{ error_list|join:", " }}
              {% endif %}
          {% endfor %}

          </strong>
      </div>
      {% endif %}
        <h2 style="padding-left: 45px;padding-bottom: 15px;" >Create an Account</h2>
        <form method="POST" action="">
          {% csrf_token  %}
          {{ form.non_field_errors }}
            <div class="form-row">
                <div class="form-group col-md-6">
                    
                    {{form.first_name}}
                </div>
                <div class="form-group col-md-6">
                  
                    {{form.last_name}}
                </div>
            </div>
            <div class="form-group">
               
                {{ form.username}}
            </div>
            <div class="form-group">
               
                {{form.email}}
            </div>
            <div class="form-group">
                
                {{form.password1}}
            </div>
            <div class="form-group">
                
                {{form.password2}}
            </div>
            <button type="submit" class="btn btn-primary">Register</button>
        </form>
        <div class="mt-4">
            <div class="d-flex justify-content-center links">
                Already have an account? <a href="{% url 'accounts:login' %}" class="ml-2">Login</a>
               
            </div>
          
        </div>
    </div>
</body>
</html>